version: "3"
services:

  prometheus:
    image: prom/prometheus:v2.0.0
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  afka_exporter:
    image: danielqsj/kafka-exporter
    command: --kafka.server=kafka03:9092
    # aws dns server
    dns: 10.173.2.9
    # dns name for kafka servers
    # use zookeeper API to get dns names for kafka server
    dns_search: us-west-1a.testdataskope.net
    ports:
      - 9308:9308

  grafana:
    image: grafana/grafana:4.6.2
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password