# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prom-stack'

scrape_configs:
  - job_name: 'prom-stack'
    static_configs:
      - targets:
        - 10.173.2.76:9091 # ec2 prometheus IP address
        - 10.173.2.76:9308 # ec2 prometheus IP address
        - 10.173.2.10:7070 # kafka server with jxm 7070 port
        - 10.173.2.11:7070 # kafka server with jxm 7070 port
        - 10.173.2.12:7070 # kafka server with jxm 7070 port